version: '3.1'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres:latest
    restart: always
    container_name: tg_bot_template_postgres
    hostname: pg_db
    env_file:
      - .env
    volumes:
      - pg_project:/var/lib/postgresql/tg_bot_template
    ports:
      - "5432:5432"

  redis_fsm:
    image: redis:latest
    hostname: redis_fsm
    env_file:
      - .env
    ports:
      - "6379:6379"

  tg_bot:
    container_name: tg_bot_template
    build: .
    env_file:
      - .env
    environment:
      # Override hosts for Docker network
      - DATABASE_HOST=pg_db
      - REDIS_HOST=redis_fsm
    restart: always
    depends_on:
      - pg_db
      - redis_fsm